/**:
  ros__parameters:
    safety:
      min_x: -30.0
      max_x: 31.0
      min_y: -7.8
      max_y: 5.0
      min_z: 1.0
      max_z: 4.0
      fence_a: 0.005
      fence_b: 2.0
      fence_p: 1.0
      obs_a:   0.5
      obs_b:   2.0
      obs_p:   1.0
      enable_viz: True
